---
title: "MetaDeformability: Osm Curve Fitting "
output: html_notebook
---


*All models are constrained to pass through (1,1)*

## Load libraries
```{r}
library(broom)
library(ggplot2)
library(dplyr)
```
## Load and transform data
```{r}
# clear workspace
rm(list = ls())

save.folder <- "../../Results/Osm_Regression"
dir.create(save.folder, showWarnings = FALSE)

#Create txt summary file
summary.file <-
    file(file.path(save.folder, paste("Osm_ExpFit_Summary.txt" , sep = "")), "wb")

SMR.Osm <- read.csv(file = "../../Data_Processed/Osm/Osm_SMR_Medians_Summary.csv",
                    header = TRUE,
                    sep = ",")
RTDC.Osm <- read.csv(file = "../../Data_Processed/Osm/Osm_RTDC_Medians_Summary.csv",
                     header = TRUE,
                     sep = ",")
DC.Osm <- read.csv(file = "../../Data_Processed/Osm/Osm_DC_Medians_Summary.csv",
                   header = TRUE,
                   sep = ",")

options("encoding" = "UTF-8")

# Combine data from different methods into single dataframe
Def.Osm = rbind(SMR.Osm, RTDC.Osm, DC.Osm)

# Add method label to each row of data
Def.Osm$Method <- c(
    rep("SMR", nrow(SMR.Osm)),
    rep("RTDC", nrow(RTDC.Osm)),
    rep("DC", nrow(DC.Osm))
    )

# Use data with Osm >= 300 (Hyperosmotic)
Def.Osm <- subset(Def.Osm, Osm >= 300)

# Normalize Osm to Isoosmotic (300)
Def.Osm$Osm <- Def.Osm$Osm / 300

```

```{r}

f.test <- function(joint.model, model.1, model.2){
    FTest.Tbl = matrix(nrow = 6, ncol = 2)
    dimnames(FTest.Tbl) = list(
        c(
            "JointModel",
            "SeparateModel",
            "Difference",
            "RelativeDifference",
            "Ratio(F)",
            "p-value"
            ),
        c("SS",
          "df"
          )
        )
    FTest.Tbl["JointModel", "SS"] <- sum(resid(joint.model) ^ 2)
    tmp <- summary(joint.model)
    FTest.Tbl["JointModel", "df"] <- tmp$df[2]
    FTest.Tbl["SeparateModel", "SS"] <- sum(c(resid(model.1), resid(model.2)) ^ 2)
    tmp1 <- summary(model.1)
    tmp2 <- summary(model.2)
    FTest.Tbl["SeparateModel", "df"] <- tmp1$df[2] + tmp2$df[2]
    FTest.Tbl["Difference", "SS"] <- FTest.Tbl["JointModel", "SS"] - FTest.Tbl["SeparateModel", "SS"]
    FTest.Tbl["Difference", "df"] <- FTest.Tbl["JointModel", "df"] - FTest.Tbl["SeparateModel", "df"]
    FTest.Tbl["RelativeDifference", "SS"] <- 100 * FTest.Tbl["Difference", "SS"] / FTest.Tbl["SeparateModel", "SS"]
    FTest.Tbl["RelativeDifference", "df"] <- 100 * FTest.Tbl["Difference", "df"] / FTest.Tbl["SeparateModel", "df"]
    FTest.Tbl["Ratio(F)", "SS"] <- FTest.Tbl["RelativeDifference", "SS"] / FTest.Tbl["RelativeDifference", "df"]
    FTest.Tbl["p-value","SS"] <-  pf(FTest.Tbl["Ratio(F)", "SS"], FTest.Tbl["Difference","df"], FTest.Tbl["SeparateModel", "df"], lower.tail= FALSE)
    
    return(FTest.Tbl)
}
```

## Fit Data with Power Model
$Def = Osm^b$
```{r}
SMR.Osm.powmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("SMR")), ], 
    formula = Relative_Deformability ~ 1 * (Osm) ^ b, 
    start = list(b = 1)
    )
DC.Osm.powmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("DC")), ],
    formula = Relative_Deformability ~ 1 * (Osm) ^ b,
    start = list(b = 1)
    )
RTDC.Osm.powmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("RTDC")), ],
    formula = Relative_Deformability ~ 1 * (Osm) ^ b,
    start = list(b = 1)
    )


Def.Osm.powmodels <- rbind(
    tidy(SMR.Osm.powmodel),
    tidy(RTDC.Osm.powmodel),
    tidy(DC.Osm.powmodel)
    )
Def.Osm.powmodels['Method'] <- c(
    rep("SMR", 1),
    rep("RTDC", 1),
    rep("DC", 1)
    )


# Open csv.file
csv.file <- file(file.path(save.folder, "Osm_Power_Coefficients.csv"), "wb")
write.csv(
    Def.Osm.powmodels,
    file = csv.file,
    row.names = FALSE
)
# Close csv.file
close(csv.file)



# Fit pairwise joint models
SMR.DC.Osm.powmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("SMR", "DC")), ],
    formula = Relative_Deformability ~ 1 * (Osm) ^ b,
    start = list(b = 1)
    )
SMR.RTDC.Osm.powmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("SMR", "RTDC")), ],
    formula = Relative_Deformability ~ 1 * (Osm) ^ b,
    start = list(b = 1)
    )
DC.RTDC.Osm.powmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("DC", "RTDC")), ],
    formula = Relative_Deformability ~ 1 * (Osm) ^ b,
    start = list(b = 1)
    )
```
## Plot Power Model Fits
```{r}
fit.size <- 100
Def.Osm.fits <- data.frame(Method=c(rep("SMR", fit.size), rep("RTDC", fit.size), rep("DC", fit.size)))
Def.Osm.fits$Osm <- c(rep((seq(300 / 300, 700 / 300, length = fit.size)), 3))

Def.Osm.fits[(Def.Osm.fits$Method %in% c("SMR")), 'Relative_Deformability.p'] <- predict(SMR.Osm.powmodel, newdata=Def.Osm.fits[(Def.Osm.fits$Method %in% c("SMR")), ])

Def.Osm.fits[(Def.Osm.fits$Method %in% c("RTDC")), 'Relative_Deformability.p'] <- predict(RTDC.Osm.powmodel, newdata=Def.Osm.fits[(Def.Osm.fits$Method %in% c("RTDC")), ])

Def.Osm.fits[(Def.Osm.fits$Method %in% c("DC")), 'Relative_Deformability.p'] <- predict(DC.Osm.powmodel, newdata=Def.Osm.fits[(Def.Osm.fits$Method %in% c("DC")), ])

ggplot(data = Def.Osm, aes(x = Osm, y = Relative_Deformability, color = Method)) +
    geom_point() +
    geom_line(data = Def.Osm.fits, aes(x = Osm, y = Relative_Deformability.p, color = Method)) +
    xlim(180 / 300, 720 / 300) +
    ylim(0, 1.4) + 
    ggtitle("Power Osm Fits")

```
## Fit Data with Exponential Model
$Def = e^{(1 - Osm)\cdot b}$
```{r}
SMR.Osm.expmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("SMR")), ],
    formula = Relative_Deformability ~ 1 * exp((1 - Osm) * b),
    start = list(b = 0)
    )
RTDC.Osm.expmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("RTDC")), ],
    formula = Relative_Deformability ~ 1 * exp((1 - Osm) * b),
    start = list(b = 0)
    )
DC.Osm.expmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("DC")), ],
    formula = Relative_Deformability ~ 1 * exp((1 - Osm) * b),
    start = list(b = 0)
    )

Def.Osm.expmodels <- rbind(
    tidy(SMR.Osm.expmodel),
    tidy(RTDC.Osm.expmodel),
    tidy(DC.Osm.expmodel)
    )
Def.Osm.expmodels['Method'] <- c(
    rep("SMR", 1),
    rep("RTDC", 1),
    rep("DC", 1)
    )

# Open csv.file
csv.file <- file(file.path(save.folder, "Osm_Exponential_Coefficients.csv"), "wb")
write.csv(
    Def.Osm.expmodels,
    file = csv.file,
    row.names = FALSE
)
# Close csv.file
close(csv.file)


write("%%%%% SUMMARY Osm exponential fit DC %%%%%", file = summary.file)
capture.output(DC.Osm.expmodel, file = summary.file , append=TRUE)
capture.output(summary(DC.Osm.expmodel), file = summary.file, append=TRUE)
write( " ",file = summary.file, append=TRUE) 

write("%%%%% SUMMARY Osm exponential fit RTDC %%%%%", file = summary.file, append=TRUE)
capture.output(RTDC.Osm.expmodel, file = summary.file, append=TRUE)
capture.output(summary(RTDC.Osm.expmodel), file = summary.file, append=TRUE)
write( " ",file = summary.file , append=TRUE) 

write("%%%%% SUMMARY Osm exponential fit SMR %%%%%", file = summary.file, append=TRUE)
capture.output(SMR.Osm.expmodel, file = summary.file, append=TRUE)
capture.output(summary(SMR.Osm.expmodel), file = summary.file, append=TRUE)
# Close summary.file
close(summary.file)
```

```{r}
# Fit pairwise joint models
SMR.DC.Osm.expmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("SMR", "DC")), ],
    formula = Relative_Deformability ~ 1 * exp((1 - Osm) * b),
    start=list(b = 0)
    )
SMR.RTDC.Osm.expmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("SMR", "RTDC")), ],
    formula = Relative_Deformability ~ 1 * exp((1 - Osm) * b),
    start = list(b = 0)
    )
DC.RTDC.Osm.expmodel <- nls(
    data = Def.Osm[(Def.Osm$Method %in% c("DC", "RTDC")), ],
    formula = Relative_Deformability ~ 1 * exp((1 - Osm) * b),
    start = list(b = 0)
    )



Def.Osm.expmodels.conf <- rbind(
    tidy(confint(SMR.Osm.expmodel)),
    tidy(confint(RTDC.Osm.expmodel)),
    tidy(confint(DC.Osm.expmodel))
    )
Def.Osm.expmodels.conf$Method <- c(rep("SMR", 2), rep("RTDC", 2), rep("DC", 2))
Def.Osm.expmodels.conf <- rename(Def.Osm.expmodels.conf, 'Coef' = 'x')
Def.Osm.expmodels.conf <- rename(Def.Osm.expmodels.conf, 'Confidence' = 'names')
# Open csv.file
csv.file <- file(file.path(save.folder, "Osm_Exponential_Coefficients_Confidence.csv"), "wb")
write.csv(
    Def.Osm.expmodels.conf,
    file = csv.file,
    row.names = FALSE
)
# Close csv.file
close(csv.file)
```

## Plot Exponential Model Fits
```{r}
fit.size <- 100
Def.Osm.fits <- data.frame(Method=c(rep("SMR",fit.size), rep("RTDC",fit.size), rep("DC",fit.size)))
Def.Osm.fits$Osm <- c(rep((seq(300 / 300, 700 / 300, length = fit.size)), 3))

Def.Osm.fits[(Def.Osm.fits$Method %in% c("SMR")), 'Relative_Deformability.p'] <- predict(
    SMR.Osm.expmodel,
    newdata = Def.Osm.fits[(Def.Osm.fits$Method %in% c("SMR")), ]
    )

Def.Osm.fits[(Def.Osm.fits$Method %in% c("RTDC")), 'Relative_Deformability.p'] <- predict(
    RTDC.Osm.expmodel,
    newdata = Def.Osm.fits[(Def.Osm.fits$Method %in% c("RTDC")), ]
    )

Def.Osm.fits[(Def.Osm.fits$Method %in% c("DC")), 'Relative_Deformability.p'] <- predict(
    DC.Osm.expmodel,
    newdata = Def.Osm.fits[(Def.Osm.fits$Method %in% c("DC")), ]
    )

ggplot(data=Def.Osm, aes(x = Osm, y = Relative_Deformability, color = Method)) +
    geom_point() +
    geom_line(data = Def.Osm.fits, aes(x = Osm, y = Relative_Deformability.p, color = Method)) +
    xlim(180 / 300, 720 / 300) +
    ylim(0, 1.4) + 
    ggtitle("Exponential Osm Fits")

```
## Fit Data with Linear Model
$(Def-1) = m\cdot (Osm-1)$

Rearrange to:

$Def = m\cdot Osm + b'$
```{r}
x0 <- 1
y0 <- 1

SMR.Osm.linmodel <- lm(
    data = Def.Osm[(Def.Osm$Method %in% c("SMR")), ], 
    formula = Relative_Deformability ~ I(Osm - 1) - 1,
    offset = rep(y0, nrow(Def.Osm[(Def.Osm$Method %in% c("SMR")), ]))
    )

RTDC.Osm.linmodel <- lm(
    data = Def.Osm[(Def.Osm$Method %in% c("RTDC")), ], Relative_Deformability ~ I(Osm - 1) - 1, 
    offset = rep(y0, nrow(Def.Osm[(Def.Osm$Method %in% c("RTDC")), ]))
    )

DC.Osm.linmodel <- lm(
    data = Def.Osm[(Def.Osm$Method %in% c("DC")), ], Relative_Deformability ~ I(Osm - 1) - 1,
    offset = rep(y0, nrow(Def.Osm[(Def.Osm$Method %in% c("DC")), ]))
    )


Def.Osm.linmodels <- rbind(
    tidy(SMR.Osm.linmodel),
    tidy(RTDC.Osm.linmodel),
    tidy(DC.Osm.linmodel)
    )
Def.Osm.linmodels['Method'] <- c(rep("SMR", 1), rep("RTDC", 1), rep("DC", 1))
Def.Osm.linmodels['m'] <- Def.Osm.linmodels['estimate']
Def.Osm.linmodels['b'] <- 1 - Def.Osm.linmodels['estimate']

# Open csv.file
csv.file <- file(file.path(save.folder, "Osm_Linear_Coefficients.csv"), "wb")
write.csv(
    Def.Osm.linmodels,
    file = csv.file,
    row.names = FALSE
)
# Close csv.file
close(csv.file)

```
## Plot Linear Model Fits
```{r}
fit.size <- 100
Def.Osm.fits <- data.frame(
    Method = c(
        rep("SMR",fit.size),
        rep("RTDC",fit.size),
        rep("DC",fit.size)
        )
    )
Def.Osm.fits$Osm <- c(rep((seq(300 / 300, 700 / 300, length = fit.size)), 3))

Def.Osm.fits[(Def.Osm.fits$Method %in% c("SMR")), 'Relative_Deformability.p'] <- predict(
    SMR.Osm.linmodel, 
    newdata = Def.Osm.fits[(Def.Osm.fits$Method %in% c("SMR")), ]
    )

Def.Osm.fits[(Def.Osm.fits$Method %in% c("RTDC")), 'Relative_Deformability.p'] <- predict(
    RTDC.Osm.linmodel,
    newdata = Def.Osm.fits[(Def.Osm.fits$Method %in% c("RTDC")), ]
    )

Def.Osm.fits[(Def.Osm.fits$Method %in% c("DC")), 'Relative_Deformability.p'] <- predict(
    DC.Osm.linmodel,
    newdata = Def.Osm.fits[(Def.Osm.fits$Method %in% c("DC")), ]
    )

ggplot(data = Def.Osm, aes(x = Osm, y = Relative_Deformability, color = Method)) +
    geom_point() +
    geom_line(data = Def.Osm.fits, aes(x = Osm, y = Relative_Deformability.p, color = Method))+
    xlim(180 / 300, 720 / 300) +
    ylim(0, 1.4) + 
    ggtitle("Linear Osm Fits")
    
```

```{r}

aic.compareTbl <- matrix(nrow = 3, ncol = 3)
dimnames(aic.compareTbl) <- list(c("Linear", "Power", "Exponential"), c("SMR", "RTDC","DC"))
aic.compareTbl["Linear", "SMR"] <- AIC(SMR.Osm.linmodel)
aic.compareTbl["Linear", "RTDC"] <- AIC(RTDC.Osm.linmodel)
aic.compareTbl["Linear", "DC"] <- AIC(DC.Osm.linmodel)
aic.compareTbl["Power", "SMR"] <- AIC(SMR.Osm.powmodel)
aic.compareTbl["Power", "RTDC"] <- AIC(RTDC.Osm.powmodel)
aic.compareTbl["Power", "DC"] <- AIC(DC.Osm.powmodel)
aic.compareTbl["Exponential", "SMR"] <- AIC(SMR.Osm.expmodel)
aic.compareTbl["Exponential", "RTDC"] <- AIC(RTDC.Osm.expmodel)
aic.compareTbl["Exponential", "DC"] <- AIC(DC.Osm.expmodel)

bic.compareTbl <- matrix(nrow = 3, ncol = 3)
dimnames(bic.compareTbl) <- list(c("Linear", "Power", "Exponential"), c("SMR", "RTDC", "DC"))
bic.compareTbl["Linear", "SMR"] <- BIC(SMR.Osm.linmodel)
bic.compareTbl["Linear", "RTDC"] <- BIC(RTDC.Osm.linmodel)
bic.compareTbl["Linear", "DC"] <- BIC(DC.Osm.linmodel)
bic.compareTbl["Power", "SMR"] <- BIC(SMR.Osm.powmodel)
bic.compareTbl["Power", "RTDC"] <- BIC(RTDC.Osm.powmodel)
bic.compareTbl["Power", "DC"] <- BIC(DC.Osm.powmodel)
bic.compareTbl["Exponential", "SMR"] <- BIC(SMR.Osm.expmodel)
bic.compareTbl["Exponential", "RTDC"] <- BIC(RTDC.Osm.expmodel)
bic.compareTbl["Exponential", "DC"] <- BIC(DC.Osm.expmodel)
# Open csv.file
csv.file <- file(file.path(save.folder, "BIC.csv"), "wb")
write.csv(
    bic.compareTbl,
    file = csv.file
)
# Close csv.file
close(csv.file)

```




## Perform pairwise Exponential Fit F-tests
```{r}
SMR.RTDC.Def.Osm.Tbl <- f.test(SMR.RTDC.Osm.expmodel, SMR.Osm.expmodel, RTDC.Osm.expmodel)
cat('SMR-RTDC F Test\n')
print(SMR.RTDC.Def.Osm.Tbl)
cat('\n')
# Open csv.file
csv.file <- file(file.path(save.folder, "SMR-RTDC_Osm_Exponential_F-Test.csv"), "wb")
write.csv(
    SMR.RTDC.Def.Osm.Tbl,
    file = csv.file
)
# Close csv.file
close(csv.file)

SMR.DC.Def.Osm.Tbl <- f.test(SMR.RTDC.Osm.expmodel, SMR.Osm.expmodel, DC.Osm.expmodel)
cat('SMR-DC F Test\n')
print(SMR.DC.Def.Osm.Tbl)
cat('\n')
# Open csv.file
csv.file <- file(file.path(save.folder, "SMR-DC_Osm_Exponential_F-Test.csv"), "wb")
write.csv(
    SMR.DC.Def.Osm.Tbl,
    file = csv.file
)
# Close csv.file
close(csv.file)


DC.RTDC.Def.Osm.Tbl <- f.test(DC.RTDC.Osm.expmodel, DC.Osm.expmodel, RTDC.Osm.expmodel)
cat('DC-RTDC F Test\n')
print(DC.RTDC.Def.Osm.Tbl)
cat('\n')
# Open csv.file
csv.file <- file(file.path(save.folder, "DC-RTDC_Osm_Exponential_F-Test.csv"), "wb")
write.csv(
    DC.RTDC.Def.Osm.Tbl,
    file = csv.file
)
# Close csv.file
close(csv.file)
```

```{r}

Def.Osm.PowerResiduals <- list('Residuals' = c(resid(SMR.Osm.powmodel), resid(DC.Osm.powmodel), resid(RTDC.Osm.powmodel)))
Def.Osm.PowerResiduals <- as.data.frame(Def.Osm.PowerResiduals)
Def.Osm.PowerResiduals$Method = c(
    rep("SMR", length(resid(SMR.Osm.powmodel))),
    rep("DC", length(resid(DC.Osm.powmodel))),
    rep("RTDC", length(resid(RTDC.Osm.powmodel)))
    )
Def.Osm.PowerResiduals$Fit = c(rep("Power", nrow(Def.Osm.PowerResiduals)))

Def.Osm.LinearResiduals <- list('Residuals' = c(resid(SMR.Osm.linmodel), resid(DC.Osm.linmodel), resid(RTDC.Osm.linmodel)))
Def.Osm.LinearResiduals <- as.data.frame(Def.Osm.LinearResiduals)
Def.Osm.LinearResiduals$Method = c(
    rep("SMR", length(resid(SMR.Osm.linmodel))),
    rep("DC", length(resid(DC.Osm.linmodel))),
    rep("RTDC", length(resid(RTDC.Osm.linmodel)))
    )
Def.Osm.LinearResiduals$Fit = c(rep("Linear", nrow(Def.Osm.LinearResiduals)))

Def.Osm.ExponentialResiduals <- list('Residuals' = c(resid(SMR.Osm.expmodel), resid(DC.Osm.expmodel), resid(RTDC.Osm.expmodel)))
Def.Osm.ExponentialResiduals <- as.data.frame(Def.Osm.ExponentialResiduals)
Def.Osm.ExponentialResiduals$Method = c(
    rep("SMR", length(resid(SMR.Osm.expmodel))),
    rep("DC", length(resid(DC.Osm.expmodel))),
    rep("RTDC", length(resid(RTDC.Osm.expmodel)))
    )
Def.Osm.ExponentialResiduals$Fit = c(rep("Exponential", nrow(Def.Osm.ExponentialResiduals)))

Def.Osm.residuals <- rbind(
    Def.Osm.LinearResiduals,
    Def.Osm.PowerResiduals,
    Def.Osm.ExponentialResiduals
    )
Def.Osm.residuals$AbsResiduals <- abs(Def.Osm.residuals$Residuals)
Def.Osm.residuals$Fit <- as.factor(Def.Osm.residuals$Fit)
Def.Osm.residuals$Method <- as.factor(Def.Osm.residuals$Method)

# Open csv.file
csv.file <- file(file.path(save.folder, "Osm_Residuals.csv"), "wb")
write.csv(
    Def.Osm.residuals,
    file = csv.file
)
# Close csv.file
close(csv.file)

ggplot(Def.Osm.residuals) + 
    geom_bar(aes(Fit, AbsResiduals, fill = Fit), position = "dodge", stat = "summary", fun.y = "median") + 
    ggtitle("Median |Residuals|")

ggplot(aes(x = Fit, y = AbsResiduals, group=Fit, fill = Fit), data = Def.Osm.residuals) + 
    geom_bar(stat = "summary", fun.y = "mean") + 
    ggtitle("Mean |Residuals|")
```
